### PR TITLE
[SVCS-541] Allow WB to log download_file/zip

### PR DESCRIPTION
**Pull request by AddisonSchiller**
## Ticket
https://openscience.atlassian.net/browse/SVCS-541

## Purpose
Remove lines stopping callbacks for `download_file/zip`.
This PR currently has a blocker.
https://openscience.atlassian.net/browse/OSF-8785 Needs to go through before this can go through.

## Changes
Removed lines stopping logs from going through

## Side effects
This is currently blocked by : https://openscience.atlassian.net/browse/OSF-8785
There is a lot of log spam/spam in general that will happen if OSF-8785 does not go through before this one.

### CODE REVIEW

**Comment by TomBaxter** [comment]
@cslzchen This is ready for next round of review.

**Comment by cslzchen** [comment]
@TomBaxter thanks bunches!

**Comment by cslzchen** [comment]
@felliott Agreed. I think either can go first since there is no blocking relationship but only merge conflicts due to the same part of code being modified.

**Comment by cslzchen** [comment]
For whoever takes this ticket: [SVCS-475](https://openscience.atlassian.net/browse/SVCS-475) with [PR-307](https://github.com/CenterForOpenScience/waterbutler/pull/307) has passed code review. If merged, there will be conflicts.

**Comment by felliott** [comment]
This looks good as-is.  The Platforms team is ready for this to go in, so merging.  No need to fix the conflicts in #307 right now, we'll worry about when we get closer.  Merging!

**Pull request closed without merging**
