### PR TITLE
Dryad Provider Pull Request

### PR DESCRIPTION
**Pull request by kwierman**
Hey, 

This is Kevin. This is a PR in anticipation of the next for for osf.io. This is the waterbutler provider for Dryad v1. I've trimmed out the unnecessary stuff, but we can create a new feature branch for the SWORD API stuff next, if you'd like.

Cheers,
Kevin

### CODE REVIEW

**Comment by lbanner** [comment]
Thank you @kwierman .... @felliott ... can you give this a look? Thanks!

**Comment by felliott** [comment]
Will do!

**Comment by felliott** [comment]
If I'm understanding the code correctly, DataDryad is currently a read-only API, and the provider just provides download links and metadata fetching, correct?  Are they planning on releasing a writable API soon?  In the meantime, we can support a read-only provider, but could you take out the stub code (upload, delete, *copy, *move), for purposes of this PR?  The base provider throws NotImplemented, and having the stub code is a little confusing for code-skimming purposes.

**Comment by felliott** [comment]
You have a `.cache` directory committed in the root of the project.  Please remove that.

**Comment by felliott** [comment]
Also please make sure you run `flake8` before push to a PR branch, our Travis build will fail early if it's not flake8-clean.

**Comment by felliott** [comment]
Finally, on WB we prefer a clean history with minimal merges.  How comfortable are you with git rebase?  I'd be happy with this whole branch being squashed down to one commit, since its all interdependent.

**Comment by kwierman** [comment]
You are correct in assuming this is a read-only provider. For the next version, we will be implementing a SWORD API similar to the Dataverse service, but since the Dryad archives live in a separate database (I think???), I implemented this to retrieve archive information only.

This will be updated in the future. I'd like to do it, but I'm open to someone else working on this as well.

If I recall correctly, leaving those code stubs will cause an error due to the `@abc.abstractmethod` decorator. I'll remove them for now, and let that sort itself out later.

**Comment by kwierman** [comment]
Haha, shoot, I managed to squash all my commit WITHOUT affecting the other commits I pulled in the interim. However, it seems I left one

**Comment by kwierman** [comment]
So, I've tried squashing this down into a single commit, but since I was pulling from cos/develop every other day, this is proving fairly challenging. Do you have any tips on how to go about doing this?

**Comment by kwierman** [comment]
All right, that should be all the changes squashed into one. I ended up using `git reset --hard HEAD~12` and `git merge --squash HEAD@{1}` since using `rebase` caused all sorts of issues.

**Comment by felliott** [comment]
Hey @kwierman,

It's getting closer, but you still have changes from develop in your branch.  Ideally what we want is to have one commit titled 'Dryad Provider Added' that branches off of current develop (c5406a0cbd7).  `merge --squash` doesn't really do that.  Working off your original PR, here's how I would do it:

1.) Here's what the project history looks like at this point:

initial-state

I generated this graph with the command `git log --graph --oneline --decorate` which I have aliased to `git hist-me`.  **95-original** is the head commit of your original PR.  **branchpoint** is the commit you branched off of to begin your work.  The first thing to do is get rid of those merge commits from develop.  To do that, we'll run an interactive rebase since **branchpoint** (4d18cd1).

2.) When you run the interactive rebase, your text editor will open with a text file that looks like this:

first-interactive-rebase-pristine

I use emacs, yours may look different.  To get rid of the merge commits, we'll remove any commits that didn't come from you, which in this case is `0df8` and `cff7`.  To omit them, comment them out like so:

first-interactive-rebase-changes

Then save this text file, and exit the editor.  Interactive rebase will use this file has a set of instructions for recreating the branch.  In this case, it adds each commit in order, but skips the two that came in from the merges.  If we run `git hist-me`  again, the new history looks like this:

new-state

3.)  Now that the merge commits are gone, we'll squash all of the commits from **branchpoint** to **95-original** into one with the command `git rebase -i branchpoint`. (Yes, this is the same command as before.  We could have done this all in one step, but when I'm rebasing, I like to break things down to multiple steps.  I find it helps keep it conceptually simple.)  This time we'll modify all abut the first commit to use the `fixup` action, which squashes it into the previous commit and discards the commit log message:

second-interactive-rebase

Save this, exit the editor, and git rebase executes the instructions. I forgot to take a screenshot at this point, but if I had run `git hist-me` you would see that **95-original** is just one commit after **branchpoint**.  If you show that commit, you'll see it contains all the changes from the original PR.

4.) Now that it's one commit, let's do a non-interactive rebase against develop to pretend like we had always been working off of it.  `git rebase origin/develop` will move your commit so that **origin/develop** is its immediate ancestor instead of **branchpoint**.  The history now looks like this:

final-history

and the stat for the commit looks like:

final-commit-stat

I've pushed the resulting commit [to a branch in my repo](https://github.com/felliott/waterbutler/tree/example/dryad-rebase) if you'd like to take a look.  Also feel free to base your work off that if you find this process annoying ^_^  .  It still has the lastfailed file, the stub upload/download code, and is missing the version pin, so you'd have to reapply those changes and then squash them down with another interactive rebase.

...and now as I try to reread this very comment, I find my eyes glazing over.  Sorry if I made things even more confusing.  If you have any questions, please let me know, I'm happy to clarify.

Cheers,
Fitz

**Comment by kwierman** [comment]
All right, commenting out commits is new to me (but cool). This seemed to have fixed my issues. The good news is that this gave me the opportunity to make the Dryad Provider v1 compatible.

In other news, I had to leave in the `upload` and `delete` method stubs. Without them defined, I get the "cannot instantiate class" error. This also is what lead me to the v1 compatibility.  Cool code design. It's kinda like programming in C++ again.

**Comment by felliott** [comment]
Unfortunately, there are still some rogue changes in the commit and we also just merged two new features into develop yesterday.  I feel bad that I keep making you update your code, so I've gone ahead and done the squash, cherry-picked the pyDryad pinning, and rebased it off of the latest develop.  I've pushed that to [a branch in my repo, `feature/dryad_provider`](https://github.com/felliott/waterbutler/tree/feature/dryad_provider).  Please clone my repo, checkout that branch, and push it to your repo.  Then, close this PR and open a new one based off of your new feature/dryad_provider branch.  I'll start reviewing the code that I have locally, and we can continue the conversation in the new PR.  Is that okay by you?

Cheers,
Fitz

**Pull request closed without merging**
