### PR TITLE
[RFR][Feature] OSF-5782 Dropbox provider root deletes

### PR DESCRIPTION
**Pull request by TomBaxter**
## Purpose
[OSF-5782](https://openscience.atlassian.net/browse/OSF-5782)
Update Dropbox provider to allow for ...
DELETE http://host:7777/v1/resources/XXXXX/providers/dropbox/

## Changes
Update def delete to check for path.is_root and call def _delete_folder_contents
Create def _delete_folder_contents to find and delete folder children

## Side effects
None

#OSF-5782

### CODE REVIEW

**Comment by felliott** [comment]
The scope of the original issue has changed.  This PR is being closed and a new PR will be opened later including this and the other delete-storage-root PRs.

**Comment by GaryKriebel** [comment]
What does this mean for the corresponding JIRA tickets?

**Comment by felliott** [comment]
They've been superseded by a master ticket OSF-5504.  I was going to leave them open for now, and close them when 5504 is merged.  I've updated each ticket with an explanation and a link back to the master ticket.

**Comment by GaryKriebel** [comment]
thanks

**Pull request closed without merging**
